/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteInterestArgs } from "./DeleteInterestArgs";
import { InterestCountArgs } from "./InterestCountArgs";
import { InterestFindManyArgs } from "./InterestFindManyArgs";
import { InterestFindUniqueArgs } from "./InterestFindUniqueArgs";
import { Interest } from "./Interest";
import { InterestService } from "../interest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Interest)
export class InterestResolverBase {
  constructor(
    protected readonly service: InterestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "read",
    possession: "any",
  })
  async _interestsMeta(
    @graphql.Args() args: InterestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Interest])
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "read",
    possession: "any",
  })
  async interests(
    @graphql.Args() args: InterestFindManyArgs
  ): Promise<Interest[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Interest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "read",
    possession: "own",
  })
  async interest(
    @graphql.Args() args: InterestFindUniqueArgs
  ): Promise<Interest | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Interest)
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "delete",
    possession: "any",
  })
  async deleteInterest(
    @graphql.Args() args: DeleteInterestArgs
  ): Promise<Interest | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
